cache:
  paths:
    - .m2/repository
    - .gradle/wrapper
    - .gradle/caches

stages:
  - deploy
  - downstream

deploy_data:
  stage: deploy
  image: openjdk:17
  script:
    - ./gradlew :surf-data:publish --stacktrace
  artifacts:
    paths:
      - build/libs/*.jar
  only:
    - master

deploy_gui:
  stage: deploy
  image: openjdk:17
  needs:
    - job: deploy_data
  script:
    - ./gradlew :surf-gui:publish --stacktrace
  artifacts:
    paths:
      - build/libs/*.jar
  only:
    - master

deploy_transaction:
  stage: deploy
  image: openjdk:17
  needs:
    - job: deploy_data
  script:
    - ./gradlew :surf-transaction:publish --stacktrace
  artifacts:
    paths:
      - build/libs/*.jar
  only:
    - master

downstream_punish:
  stage: downstream
  allow_failure: true
  only:
    refs:
      - master
  trigger:
    project: "surf/surf-punish"
    strategy: depend