cache:
  paths:
    - .m2/repository
    - .gradle/wrapper
    - .gradle/caches

stages:
  - deploy

before_script:
  - "chmod +x gradlew"

deploy:
  stage: deploy
  image: openjdk:21
  script:
    - ./gradlew publish
  artifacts:
    paths:
      - build/libs/*.jar
  only:
    - master